package com.bdk.mapper;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_menu.MENU_ID
     *
     * @mbg.generated
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_menu.MANU_NAME
     *
     * @mbg.generated
     */
    private String manuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_menu.MANU_PATH
     *
     * @mbg.generated
     */
    private String manuPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_menu.PARENT_ID
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_menu.MARK
     *
     * @mbg.generated
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_menu.STATE
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_menu.ICON_CLS
     *
     * @mbg.generated
     */
    private String iconCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_menu.MENU_ID
     *
     * @return the value of p_menu.MENU_ID
     *
     * @mbg.generated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_menu.MENU_ID
     *
     * @param menuId the value for p_menu.MENU_ID
     *
     * @mbg.generated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_menu.MANU_NAME
     *
     * @return the value of p_menu.MANU_NAME
     *
     * @mbg.generated
     */
    public String getManuName() {
        return manuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_menu.MANU_NAME
     *
     * @param manuName the value for p_menu.MANU_NAME
     *
     * @mbg.generated
     */
    public void setManuName(String manuName) {
        this.manuName = manuName == null ? null : manuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_menu.MANU_PATH
     *
     * @return the value of p_menu.MANU_PATH
     *
     * @mbg.generated
     */
    public String getManuPath() {
        return manuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_menu.MANU_PATH
     *
     * @param manuPath the value for p_menu.MANU_PATH
     *
     * @mbg.generated
     */
    public void setManuPath(String manuPath) {
        this.manuPath = manuPath == null ? null : manuPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_menu.PARENT_ID
     *
     * @return the value of p_menu.PARENT_ID
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_menu.PARENT_ID
     *
     * @param parentId the value for p_menu.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_menu.MARK
     *
     * @return the value of p_menu.MARK
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_menu.MARK
     *
     * @param mark the value for p_menu.MARK
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_menu.STATE
     *
     * @return the value of p_menu.STATE
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_menu.STATE
     *
     * @param state the value for p_menu.STATE
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_menu.ICON_CLS
     *
     * @return the value of p_menu.ICON_CLS
     *
     * @mbg.generated
     */
    public String getIconCls() {
        return iconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_menu.ICON_CLS
     *
     * @param iconCls the value for p_menu.ICON_CLS
     *
     * @mbg.generated
     */
    public void setIconCls(String iconCls) {
        this.iconCls = iconCls == null ? null : iconCls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_menu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", manuName=").append(manuName);
        sb.append(", manuPath=").append(manuPath);
        sb.append(", parentId=").append(parentId);
        sb.append(", mark=").append(mark);
        sb.append(", state=").append(state);
        sb.append(", iconCls=").append(iconCls);
        sb.append("]");
        return sb.toString();
    }
}