package com.bdk.dao;

import com.bdk.mapper.Menu;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_menu
     *
     * @mbg.generated
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_menu
     *
     * @mbg.generated
     */
    int insertSelective(Menu record);
}