package com.bdk.dao;

import com.bdk.mapper.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role
     *
     * @mbg.generated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role
     *
     * @mbg.generated
     */
    int insertSelective(Role record);
}