package com.bdk.dao;

import com.bdk.mapper.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);
}